[2024-07-23T07:52:54.777+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: test_braching_etl_daily.transform_and_load_task manual__2024-07-23T07:52:51.028043+00:00 [queued]>
[2024-07-23T07:52:54.786+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: test_braching_etl_daily.transform_and_load_task manual__2024-07-23T07:52:51.028043+00:00 [queued]>
[2024-07-23T07:52:54.788+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-23T07:52:54.804+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-23 07:52:51.028043+00:00
[2024-07-23T07:52:54.811+0000] {standard_task_runner.py:60} INFO - Started process 7596 to run task
[2024-07-23T07:52:54.815+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'test_braching_etl_daily', 'transform_and_load_task', 'manual__2024-07-23T07:52:51.028043+00:00', '--job-id', '303', '--raw', '--subdir', 'DAGS_FOLDER/test_braching.py', '--cfg-path', '/tmp/tmpixb1k8b3']
[2024-07-23T07:52:54.818+0000] {standard_task_runner.py:88} INFO - Job 303: Subtask transform_and_load_task
[2024-07-23T07:52:54.910+0000] {task_command.py:423} INFO - Running <TaskInstance: test_braching_etl_daily.transform_and_load_task manual__2024-07-23T07:52:51.028043+00:00 [running]> on host 087c584822ad
[2024-07-23T07:52:55.013+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='test_braching_etl_daily' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-23T07:52:51.028043+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-23T07:52:51.028043+00:00'
[2024-07-23T07:52:55.017+0000] {logging_mixin.py:188} INFO - Start data transformation and load stage
[2024-07-23T07:52:55.021+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_braching.py", line 55, in transform_and_load_task
    gcp_options.pickle_library = 'cloudpickle'
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/options/pipeline_options.py", line 495, in __setattr__
    raise AttributeError(
AttributeError: 'GoogleCloudOptions' object has no attribute 'pickle_library'
[2024-07-23T07:52:55.040+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=test_braching_etl_daily, task_id=transform_and_load_task, execution_date=20240723T075251, start_date=20240723T075254, end_date=20240723T075255
[2024-07-23T07:52:55.052+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 303 for task transform_and_load_task ('GoogleCloudOptions' object has no attribute 'pickle_library'; 7596)
[2024-07-23T07:52:55.067+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-23T07:52:55.083+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
