[2024-07-16T09:47:13.658+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:47:09.687491+00:00 [queued]>
[2024-07-16T09:47:13.669+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:47:09.687491+00:00 [queued]>
[2024-07-16T09:47:13.670+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-16T09:47:13.686+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-16 09:47:09.687491+00:00
[2024-07-16T09:47:13.693+0000] {standard_task_runner.py:60} INFO - Started process 395 to run task
[2024-07-16T09:47:13.699+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'transform_and_load_task', 'manual__2024-07-16T09:47:09.687491+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmpmkn9afbz']
[2024-07-16T09:47:13.702+0000] {standard_task_runner.py:88} INFO - Job 91: Subtask transform_and_load_task
[2024-07-16T09:47:13.763+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:47:09.687491+00:00 [running]> on host 3e75606cfc9c
[2024-07-16T09:47:13.863+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T09:47:09.687491+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T09:47:09.687491+00:00'
[2024-07-16T09:47:13.869+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 40, in transform_and_load_task
    run_pipeline_beam(avro_file_pattern, table_spec, schema, unique_key)
  File "/opt/airflow/plugins/modules/transformation_load_stage.py", line 101, in run_pipeline
    options.view_as(StandardOptions).save_main_session = True
  File "/home/airflow/.local/lib/python3.8/site-packages/apache_beam/options/pipeline_options.py", line 495, in __setattr__
    raise AttributeError(
AttributeError: 'StandardOptions' object has no attribute 'save_main_session'
[2024-07-16T09:47:13.892+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=transform_and_load_task, execution_date=20240716T094709, start_date=20240716T094713, end_date=20240716T094713
[2024-07-16T09:47:13.906+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 91 for task transform_and_load_task ('StandardOptions' object has no attribute 'save_main_session'; 395)
[2024-07-16T09:47:13.952+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T09:47:13.972+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
