[2024-07-16T09:19:37.740+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:19:33.992454+00:00 [queued]>
[2024-07-16T09:19:37.753+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:19:33.992454+00:00 [queued]>
[2024-07-16T09:19:37.754+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-07-16T09:19:37.771+0000] {taskinstance.py:2191} INFO - Executing <Task(_PythonDecoratedOperator): transform_and_load_task> on 2024-07-16 09:19:33.992454+00:00
[2024-07-16T09:19:37.779+0000] {standard_task_runner.py:60} INFO - Started process 725 to run task
[2024-07-16T09:19:37.784+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'dim_product', 'transform_and_load_task', 'manual__2024-07-16T09:19:33.992454+00:00', '--job-id', '84', '--raw', '--subdir', 'DAGS_FOLDER/dim_product_orchestration.py', '--cfg-path', '/tmp/tmp6lrskmcz']
[2024-07-16T09:19:37.786+0000] {standard_task_runner.py:88} INFO - Job 84: Subtask transform_and_load_task
[2024-07-16T09:19:37.863+0000] {task_command.py:423} INFO - Running <TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T09:19:33.992454+00:00 [running]> on host 690a34bdb89f
[2024-07-16T09:19:37.969+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dim_product' AIRFLOW_CTX_TASK_ID='transform_and_load_task' AIRFLOW_CTX_EXECUTION_DATE='2024-07-16T09:19:33.992454+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-16T09:19:33.992454+00:00'
[2024-07-16T09:19:37.972+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 241, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dim_product_orchestration.py", line 38, in transform_and_load_task
    run_pipeline_beam(avro_file_pattern, table_spec, schema, unique_key)
  File "/opt/airflow/plugins/modules/transformation_load_stage.py", line 89, in run_pipeline
    sys.path.append('/path/to/your/module')
NameError: name 'sys' is not defined
[2024-07-16T09:19:37.995+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=dim_product, task_id=transform_and_load_task, execution_date=20240716T091933, start_date=20240716T091937, end_date=20240716T091937
[2024-07-16T09:19:38.012+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 84 for task transform_and_load_task (name 'sys' is not defined; 725)
[2024-07-16T09:19:38.037+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2024-07-16T09:19:38.066+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
