[2024-07-16T17:47:50.716+0000] {scheduler_job_runner.py:781} ERROR - Executor reports task instance <TaskInstance: dim_product.transform_and_load_task manual__2024-07-16T17:47:48.660309+00:00 [queued]> finished (failed) although the task says it's queued. (Info: None) Was the task killed externally?
